name: CI - Quality Checks and Build

on:
  push:
    branches:
      - "feature/**"
      - "fix/**"
      - "hotfix/**"
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  # Fast feedback: Run tests and linting in parallel
  quality:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        check: [lint, test]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        if: matrix.check == 'lint'
        run: npm run lint

      - name: Run tests
        if: matrix.check == 'test'
        run: npm test

  # Build after quality checks pass
  build:
    runs-on: ubuntu-latest
    needs: quality

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/
          retention-days: 1
